name: Compile and Deploy

on:
    push:
        branches: 
        - master

jobs:
    compile:
        permissions:
            contents: read
            pull-requests: write
        uses: projects-mannulus/templates/.github/workflows/angular-compile.yml@main
        with:
            nodeVersion: '18.x'
            baseHref: auth-front
